version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi
    deploy:
      replicas: 4
    expose:
      - 3000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
